### ISSUE TITLE
关于数据库脚本及数据库配置文件

### ISSUE THREAD

**Issue by jiayuanrelian** [ls960972314/report#2]
在report-web-admin，report-web-query中都有jdbc.properties这个文件，在配置这个文件中预定义了两个数据库连接的配置分别是jdbc_url=jdbc:mysql://xxx和pos_url=jdbc:mysql://xxx，这两个数据库所对应的数据库初始化脚本能否提供一下呢？
谢谢

**Comment by ls960972314** [comment]
report-web-query暂时没用(没重构完)，至于jdbc_url是要连接你们自己的数据库哦，数据库脚本我下午传进去

**Comment by ls960972314** [comment]
在database目录下
