### ISSUE TITLE
无法登录演示地址

### ISSUE THREAD

**Issue by chaiziqi** [ls960972314/report#5]
你好，visitor账户，密码123456，登录提示：您输入的帐号或密码有误，或者是使用域账户登录时未找到匹配的域控服务器配置。 @ls960972314

**Comment by ls960972314** [comment]
抱歉啊，腾讯云到期了，没想到现在还有这么多人需要，抽时间我重新搭下

**Comment by chaiziqi** [comment]
非常感谢！

**Comment by ls960972314** [comment]
可以访问了
